/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    control: {
        "#mytable": {
            rowclick: 'onMytableRowClick'
        }
    },

    onMytableRowClick: function(tableview, record, tr, rowIndex, e, eOpts) {
        //Ext.Msg.alert('Info', 'Click en '+record.id);
        //Ext.getCmp('myform').loadRecord(record); no funciona en cotroller?

        //peticion ajax para verificar datos
        Ext.Ajax.request({
            url:'api/recipes/'+record.id+'.json',
            success: function(response){
                var result = Ext.decode(response.responseText);
                var value=result.recipe;
                //getValue(value);
                Ext.Msg.alert('Info', 'Click en '+value.name);

                //Ext.getCmp('myform').getForm().setValues({
                //   name: value.name,
                //   id: value.id
                //});
                //var name = Ext.getCmp('name').setValue(value.name);
            }
        });
    }

});
