/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'MyApp.view.MyViewportViewController',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.toolbar.Paging',
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'myviewport',
    viewModel: {
        type: 'myviewport'
    },

    items: [
        {
            xtype: 'panel',
            height: 516,
            title: 'My Panel en CakePHP',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    height: 287,
                    width: '100%',
                    title: 'My Grid Panel',
                    autoLoad: true,
                    store: 'Recipes',
                    viewConfig: {
                        itemId: 'mytable'
                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            width: 48,
                            dataIndex: 'id',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 171,
                            dataIndex: 'name',
                            text: 'Name'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 153,
                            dataIndex: 'created',
                            text: 'Created',
                            format: 'm/j/Y g:i A'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'modified',
                            text: 'Modified',
                            format: 'm/j/Y'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'Recipes'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    flex: 1,
                    reference: 'form',
                    itemId: 'myform',
                    width: 200,
                    bodyPadding: 10,
                    title: 'My Form',
                    method: 'POST',
                    url: 'api/recipes.json',
                    items: [
                        {
                            xtype: 'displayfield',
                            itemId: 'txtId',
                            fieldLabel: 'ID',
                            name: 'id'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'txtName',
                            width: 425,
                            fieldLabel: 'Name',
                            name: 'name'
                        },
                        {
                            xtype: 'container',
                            padding: 10,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    formBind: true,
                                    itemId: 'saveButton',
                                    margin: 5,
                                    text: 'Save',
                                    listeners: {
                                        click: 'onSave'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    itemId: 'cancelButton',
                                    margin: 5,
                                    text: 'Cancel',
                                    listeners: {
                                        click: 'onCancel'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});