/*
 * File: app/view/MyViewportViewModel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewportViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.myviewport',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        recipes: {
            model: 'MyApp.model.Recipe',
            data: [
                {
                    id: 720,
                    name: 'quasi',
                    created: '6/15/2012',
                    modified: '5/5/2011'
                },
                {
                    id: 206,
                    name: 'non',
                    created: '7/26/2007',
                    modified: '6/18/2014'
                },
                {
                    id: 461,
                    name: 'excepturi',
                    created: '1/17/2007',
                    modified: '4/19/2004'
                },
                {
                    id: 488,
                    name: 'quis',
                    created: '5/3/2009',
                    modified: '2/25/2003'
                },
                {
                    id: 609,
                    name: 'et',
                    created: '12/8/2008',
                    modified: '1/9/2009'
                },
                {
                    id: 71,
                    name: 'alias',
                    created: '12/12/2011',
                    modified: '11/19/2010'
                },
                {
                    id: 313,
                    name: 'dicta',
                    created: '9/20/2011',
                    modified: '3/15/2011'
                },
                {
                    id: 814,
                    name: 'quis',
                    created: '7/15/2001',
                    modified: '5/4/2002'
                },
                {
                    id: 803,
                    name: 'praesentium',
                    created: '9/3/2007',
                    modified: '1/18/2007'
                },
                {
                    id: 1000,
                    name: 'quas',
                    created: '3/22/2013',
                    modified: '8/16/2002'
                },
                {
                    id: 888,
                    name: 'molestias',
                    created: '12/9/2013',
                    modified: '5/21/2007'
                },
                {
                    id: 650,
                    name: 'et',
                    created: '11/7/2002',
                    modified: '10/1/2012'
                },
                {
                    id: 259,
                    name: 'odit',
                    created: '8/17/2010',
                    modified: '12/7/2010'
                },
                {
                    id: 458,
                    name: 'minima',
                    created: '4/27/2005',
                    modified: '4/24/2002'
                },
                {
                    id: 149,
                    name: 'minima',
                    created: '10/14/2009',
                    modified: '6/6/2007'
                },
                {
                    id: 517,
                    name: 'nemo',
                    created: '3/16/2009',
                    modified: '6/1/2009'
                },
                {
                    id: 977,
                    name: 'voluptatem',
                    created: '4/25/2004',
                    modified: '10/9/2001'
                },
                {
                    id: 823,
                    name: 'quo',
                    created: '1/21/2010',
                    modified: '12/22/2013'
                },
                {
                    id: 264,
                    name: 'possimus',
                    created: '7/18/2011',
                    modified: '5/26/2011'
                },
                {
                    id: 270,
                    name: 'et',
                    created: '9/26/2011',
                    modified: '9/2/2013'
                },
                {
                    id: 224,
                    name: 'sint',
                    created: '1/28/2013',
                    modified: '5/4/2008'
                },
                {
                    id: 624,
                    name: 'consectetur',
                    created: '10/19/2008',
                    modified: '6/3/2011'
                },
                {
                    id: 225,
                    name: 'consequatur',
                    created: '3/23/2012',
                    modified: '4/26/2014'
                },
                {
                    id: 856,
                    name: 'laborum',
                    created: '2/7/2006',
                    modified: '3/27/2014'
                },
                {
                    id: 72,
                    name: 'accusantium',
                    created: '3/25/2001',
                    modified: '2/5/2007'
                },
                {
                    id: 725,
                    name: 'vel',
                    created: '2/15/2009',
                    modified: '2/15/2005'
                },
                {
                    id: 372,
                    name: 'laboriosam',
                    created: '4/16/2001',
                    modified: '5/10/2013'
                },
                {
                    id: 441,
                    name: 'numquam',
                    created: '11/2/2001',
                    modified: '5/25/2013'
                },
                {
                    id: 659,
                    name: 'ex',
                    created: '6/4/2011',
                    modified: '2/19/2002'
                },
                {
                    id: 845,
                    name: 'nemo',
                    created: '11/13/2004',
                    modified: '1/4/2008'
                }
            ],
            proxy: {
                type: 'memory'
            }
        },
        recipes: {
            model: 'MyApp.model.Recipe',
            data: [
                {
                    id: 412,
                    name: 'ut'
                },
                {
                    id: 38,
                    name: 'ut'
                },
                {
                    id: 522,
                    name: 'laborum'
                },
                {
                    id: 168,
                    name: 'eaque'
                },
                {
                    id: 631,
                    name: 'tempora'
                },
                {
                    id: 388,
                    name: 'nihil'
                },
                {
                    id: 24,
                    name: 'ad'
                },
                {
                    id: 470,
                    name: 'qui'
                },
                {
                    id: 698,
                    name: 'dolores'
                },
                {
                    id: 545,
                    name: 'cum'
                },
                {
                    id: 347,
                    name: 'explicabo'
                },
                {
                    id: 427,
                    name: 'eligendi'
                },
                {
                    id: 780,
                    name: 'fugit'
                },
                {
                    id: 707,
                    name: 'quia'
                },
                {
                    id: 208,
                    name: 'esse'
                },
                {
                    id: 230,
                    name: 'nam'
                },
                {
                    id: 625,
                    name: 'harum'
                },
                {
                    id: 667,
                    name: 'sed'
                },
                {
                    id: 847,
                    name: 'occaecati'
                },
                {
                    id: 499,
                    name: 'inventore'
                },
                {
                    id: 313,
                    name: 'sapiente'
                },
                {
                    id: 681,
                    name: 'quo'
                },
                {
                    id: 339,
                    name: 'alias'
                },
                {
                    id: 155,
                    name: 'cumque'
                },
                {
                    id: 33,
                    name: 'ut'
                },
                {
                    id: 210,
                    name: 'maxime'
                },
                {
                    id: 189,
                    name: 'sapiente'
                },
                {
                    id: 782,
                    name: 'autem'
                },
                {
                    id: 527,
                    name: 'eum'
                },
                {
                    id: 473,
                    name: 'sed'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});